/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.neu.assingment1.my_package;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.neu.assingment1.model.EmployeeFunctionality;
import com.neu.assingment1.model.Employee;
import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import java.util.regex.Pattern;

        
/**
 *
 * @author shubhamjain
 */
public class EmployeeManagementPortal extends javax.swing.JFrame {

    
    EmployeeFunctionality add_emp;
    private TableRowSorter<DefaultTableModel> sorter;
    
    //regex for employee name
    private static final String name_regex ="^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$";
    private static final Pattern name_pattern = Pattern.compile(name_regex);
        
    //regex for employee email
    private static final String email_regex =
            "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*" +
            "@" + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    private static final Pattern email_pattern = Pattern.compile(email_regex);
    
    
    // regex for india/us phone number with or without dashes
    private static final String phone_regex =
            "^\\D?(\\d{3})\\D?\\D?(\\d{3})\\D?(\\d{4})$";
    private static final Pattern phone_pattern = Pattern.compile(phone_regex);

    public EmployeeManagementPortal() {
                initComponents();
                add_emp= new EmployeeFunctionality();

                 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        addPage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmployeeAge = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmployeePosition = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmployeeStartDate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEmployeeTeam = new javax.swing.JTextField();
        txtEmployeeGender = new javax.swing.JComboBox<>();
        txtEmployeeLevel = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtEmployeeContactNo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmployeeEmailID = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        addCancelBtn = new javax.swing.JButton();
        test = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        deletePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        delEmployeeID = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        deleteCancelBtn = new javax.swing.JButton();
        searchPage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        searchCancelBtn = new javax.swing.JButton();
        editPage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        editCancelBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        editEmployeeContactNo = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        editEmployeeStartDate = new javax.swing.JTextField();
        editEmployeePosition = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        editEmployeeEmailID = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        editEmployeeGender = new javax.swing.JComboBox<>();
        jLabel47 = new javax.swing.JLabel();
        editEmployeeTeam = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        editEmployeeAge = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        editEmployeeLevel = new javax.swing.JComboBox<>();
        jLabel50 = new javax.swing.JLabel();
        editEmployeeName = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        editEmployeeID = new javax.swing.JTextField();
        tablePage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        viewPage = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        viewEmployeeName = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        viewEmployeeID = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        viewEmployeeAge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        viewEmployeeLevel = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        viewEmployeeGender = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        viewEmployeeTeam = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        viewEmployeeEmailID = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        viewEmployeePosition = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        viewEmployeeContactNo = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        viewEmployeeStartDate = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        viewProfilePhoto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Employee Management Portal");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("Add Employees");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Name");

        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Employee ID");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Gender");

        txtEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeAgeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Age");

        txtEmployeePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeePositionActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("Position Title");

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setText("Level");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Start date");

        txtEmployeeStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeStartDateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Team Info");

        txtEmployeeTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeTeamActionPerformed(evt);
            }
        });

        txtEmployeeGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        txtEmployeeGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeGenderActionPerformed(evt);
            }
        });

        txtEmployeeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", " " }));
        txtEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeLevelActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Email ID");

        txtEmployeeContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeContactNoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Contact number");

        txtEmployeeEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeEmailIDActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        addCancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addCancelBtn.setText("Cancel");
        addCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCancelBtnActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel20.setText("Photo");

        button1.setLabel("Upload Photo");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPageLayout = new javax.swing.GroupLayout(addPage);
        addPage.setLayout(addPageLayout);
        addPageLayout.setHorizontalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPageLayout.createSequentialGroup()
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel5))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addPageLayout.createSequentialGroup()
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(addPageLayout.createSequentialGroup()
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtEmployeeContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                .addComponent(txtEmployeeEmailID)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(addPageLayout.createSequentialGroup()
                                        .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8)))
                                .addGap(18, 18, 18)
                                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(333, Short.MAX_VALUE))
                    .addGroup(addPageLayout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        addPageLayout.setVerticalGroup(
            addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(41, 41, 41)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(txtEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addGroup(addPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPageLayout.createSequentialGroup()
                        .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
        );

        jTabbedPane1.addTab("Add", addPage);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Management Portal");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel17.setText("Delete Employees");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel18.setText("Enter the Employee ID to Delete");

        deleteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        deleteCancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        deleteCancelBtn.setText("Cancel");
        deleteCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deletePageLayout = new javax.swing.GroupLayout(deletePage);
        deletePage.setLayout(deletePageLayout);
        deletePageLayout.setHorizontalGroup(
            deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletePageLayout.createSequentialGroup()
                .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(deleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(jLabel1))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(delEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        deletePageLayout.setVerticalGroup(
            deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletePageLayout.createSequentialGroup()
                .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deletePageLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(99, 99, 99)
                        .addGroup(deletePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(0, 213, Short.MAX_VALUE)))
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Delete", deletePage);

        jLabel3.setText("Search for Employees by their ID, Name, Email or any other field");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Employee Management Portal");

        searchBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        searchCancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        searchCancelBtn.setText("Cancel");
        searchCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPageLayout = new javax.swing.GroupLayout(searchPage);
        searchPage.setLayout(searchPageLayout);
        searchPageLayout.setHorizontalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPageLayout.createSequentialGroup()
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel6))
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPageLayout.createSequentialGroup()
                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193)
                                .addComponent(searchCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchPageLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel3)))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        searchPageLayout.setVerticalGroup(
            searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPageLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(searchPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        jTabbedPane1.addTab("Search", searchPage);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Employee Management Portal");

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel19.setText("Edit Employees");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editCancelBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        editCancelBtn.setText("Cancel");
        editCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCancelBtnActionPerformed(evt);
            }
        });

        editBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel42.setText("Contact number");

        editEmployeeContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeContactNoActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel43.setText("Start date");

        editEmployeeStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeStartDateActionPerformed(evt);
            }
        });

        editEmployeePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeePositionActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel44.setText("Position Title");

        editEmployeeEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeEmailIDActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel45.setText("Email ID");

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel46.setText("Gender");

        editEmployeeGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        editEmployeeGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeGenderActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel47.setText("Team Info");

        editEmployeeTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeTeamActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel48.setText("Age");

        editEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeAgeActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel49.setText("Level");

        editEmployeeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3" }));
        editEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeLevelActionPerformed(evt);
            }
        });

        jLabel50.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel50.setText("Name");

        editEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeNameActionPerformed(evt);
            }
        });

        jLabel51.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel51.setText("Employee ID");

        javax.swing.GroupLayout editPageLayout = new javax.swing.GroupLayout(editPage);
        editPage.setLayout(editPageLayout);
        editPageLayout.setHorizontalGroup(
            editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPageLayout.createSequentialGroup()
                .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel2))
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel19))
                    .addGroup(editPageLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(editEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(484, Short.MAX_VALUE))
            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPageLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel50)
                        .addComponent(jLabel48)
                        .addComponent(jLabel46)
                        .addComponent(jLabel45)
                        .addComponent(jLabel42))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addComponent(editEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jLabel51)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addComponent(editEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(208, 208, 208)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel47)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPageLayout.createSequentialGroup()
                                            .addComponent(jLabel49)
                                            .addGap(1, 1, 1))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, editPageLayout.createSequentialGroup()
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(editEmployeeContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(editEmployeeEmailID))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(editEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(editPageLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(editEmployeeStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                        .addComponent(editEmployeePosition)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPageLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(editEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(editPageLayout.createSequentialGroup()
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(editCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(309, Short.MAX_VALUE)))
        );
        editPageLayout.setVerticalGroup(
            editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPageLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(87, 87, 87)
                .addComponent(editEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 307, Short.MAX_VALUE))
            .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editPageLayout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel50)
                        .addComponent(editEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel51)
                        .addComponent(editEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel48)
                        .addComponent(editEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel49))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47)
                        .addComponent(editEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel46)
                        .addComponent(editEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44)
                        .addComponent(editEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel45)
                        .addComponent(editEmployeeEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(editEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42)
                            .addComponent(editEmployeeContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                    .addGroup(editPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editCancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(48, 48, 48)))
        );

        jTabbedPane1.addTab("Edit", editPage);

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Team Info", "Level", "Position", "Phone", "Email ID", "Photo"
            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        javax.swing.GroupLayout tablePageLayout = new javax.swing.GroupLayout(tablePage);
        tablePage.setLayout(tablePageLayout);
        tablePageLayout.setHorizontalGroup(
            tablePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
        );
        tablePageLayout.setVerticalGroup(
            tablePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Table", tablePage);

        viewPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPageMouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel21.setText("Name");

        viewEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeNameActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel22.setText("Employee ID");

        jLabel23.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel23.setText("Age");

        viewEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeAgeActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel24.setText("Level");

        viewEmployeeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", " " }));
        viewEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeLevelActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel25.setText("Gender");

        viewEmployeeGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        viewEmployeeGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeGenderActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel26.setText("Team Info");

        viewEmployeeTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeTeamActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel27.setText("Email ID");

        viewEmployeeEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeEmailIDActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel28.setText("Position Title");

        viewEmployeePosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeePositionActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel29.setText("Contact number");

        viewEmployeeContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeContactNoActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel30.setText("Start date");

        viewEmployeeStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeeStartDateActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel31.setText("Employee Photo");

        viewProfilePhoto1.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout viewPageLayout = new javax.swing.GroupLayout(viewPage);
        viewPage.setLayout(viewPageLayout);
        viewPageLayout.setHorizontalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPageLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29))
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewPageLayout.createSequentialGroup()
                                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(viewEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(viewEmployeeContactNo)
                                        .addComponent(viewEmployeeEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(viewPageLayout.createSequentialGroup()
                                .addComponent(viewEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(jLabel22)))
                        .addGap(18, 18, 18)
                        .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(281, 281, 281))
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewProfilePhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        viewPageLayout.setVerticalGroup(
            viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPageLayout.createSequentialGroup()
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPageLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel31)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewProfilePhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(viewEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(viewEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(viewEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(viewEmployeeTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(viewEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEmployeeEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(viewEmployeePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEmployeeContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(viewEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", viewPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCancelBtnActionPerformed
        searchField.setText("");

        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        sorter = new TableRowSorter<>(model);
        employeeTable.setRowSorter(sorter);
        sorter.setRowFilter(null);
        jTabbedPane1.setSelectedIndex(4);

        // TODO add your handling code here:
    }//GEN-LAST:event_searchCancelBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        sorter = new TableRowSorter<>(model);
        employeeTable.setRowSorter(sorter);
        String searchText= searchField.getText();
        if(searchText.length()==0){
            sorter.setRowFilter(null);
        }
        else{
            sorter.setRowFilter(RowFilter.regexFilter(searchText));
            jTabbedPane1.setSelectedIndex(4);

        }

//        String searchText= searchField.getText();
//        for(Employee emp: add_emp.getEmployee_list() ){
//            if(searchText.equalsIgnoreCase(emp.getEmployeeID()) || searchText.equalsIgnoreCase(emp.getName()) || searchText.equalsIgnoreCase(emp.getEmailID() )){
//               add_emp.getEmployee_list();
//                System.out.println("searched successfully");
//                employeeTable();
//                break;                
//            }
//        }

        

        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        int selected = employeeTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        
        
        //code for the edit screen
        editEmployeeName.setText(model.getValueAt(selected,0).toString());
        editEmployeeID.setText(model.getValueAt(selected,1).toString());
        editEmployeeAge.setText(model.getValueAt(selected,2).toString());
        String emp_gender = model.getValueAt(selected, 3).toString();
        switch(emp_gender){
            case "Male" -> {
                editEmployeeGender.setSelectedIndex(0);
                break;
            }
            case "Female" ->{
                editEmployeeGender.setSelectedIndex(1);
                break;

            }

        }
        editEmployeeStartDate.setText(model.getValueAt(selected,4).toString());
        editEmployeeTeam.setText(model.getValueAt(selected,5).toString());
        String emp_level = model.getValueAt(selected, 6).toString();
        switch(emp_level){
            case "Level 1" -> {
                editEmployeeLevel.setSelectedIndex(0);
                break;
            }
            case "Level 2" ->{
                editEmployeeLevel.setSelectedIndex(1);
                break;

            }

            case "Level 3" ->{
                editEmployeeLevel.setSelectedIndex(2);
                break;

            }
          

        }

        editEmployeePosition.setText(model.getValueAt(selected,7).toString());
        editEmployeeContactNo.setText(model.getValueAt(selected,8).toString());
        editEmployeeEmailID.setText(model.getValueAt(selected,9).toString());
        
 
        
        
        
        
        //code for the viewscreen
        
        viewEmployeeName.setText(model.getValueAt(selected,0).toString());
        viewEmployeeID.setText(model.getValueAt(selected,1).toString());
        viewEmployeeAge.setText(model.getValueAt(selected,2).toString());
        String view_emp_gender = model.getValueAt(selected, 3).toString();
        switch(view_emp_gender){
            case "Male" -> {
                viewEmployeeGender.setSelectedIndex(0);
                break;
            }
            case "Female" ->{
                viewEmployeeGender.setSelectedIndex(1);
                break;

            }

        }
        viewEmployeeStartDate.setText(model.getValueAt(selected,4).toString());
        viewEmployeeTeam.setText(model.getValueAt(selected,5).toString());
        String view_emp_level = model.getValueAt(selected, 6).toString();
        switch(view_emp_level){
            case "Level 1" -> {
                viewEmployeeLevel.setSelectedIndex(0);
                break;
            }
            case "Level 2" ->{
                viewEmployeeLevel.setSelectedIndex(1);
                break;

            }

            case "Level 3" ->{
                viewEmployeeLevel.setSelectedIndex(2);
                break;

            }
           

        }

        viewEmployeePosition.setText(model.getValueAt(selected,7).toString());
        viewEmployeeContactNo.setText(model.getValueAt(selected,8).toString());
        viewEmployeeEmailID.setText(model.getValueAt(selected,9).toString());
        ImageIcon i = new ImageIcon(model.getValueAt(selected,10).toString());
        Image image = i.getImage().getScaledInstance(viewProfilePhoto1.getWidth(), viewProfilePhoto1.getHeight(), Image.SCALE_SMOOTH);
        viewProfilePhoto1.setIcon(new ImageIcon(image));
        viewEmployeeName.setEnabled(false);
        viewEmployeeID.setEnabled(false);
        viewEmployeeAge.setEnabled(false);
        viewEmployeeGender.setEnabled(false);
        viewEmployeeStartDate.setEnabled(false);
        viewEmployeeTeam.setEnabled(false);
        viewEmployeeLevel.setEnabled(false);
        viewEmployeePosition.setEnabled(false);
        viewEmployeeContactNo.setEnabled(false);
        viewEmployeeEmailID.setEnabled(false);

        

        
        
        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_employeeTableMouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","png","jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result==JFileChooser.APPROVE_OPTION){
            File selected = file.getSelectedFile();
            String path = selected.getAbsolutePath();
            add_emp.setImgPath(path);
            JOptionPane.showMessageDialog(null,"Profile photo added successfully");

            
//            ImageIcon i = new ImageIcon(path);
//            Image image = i.getImage().getScaledInstance(viewProfilePhoto1.getWidth(), viewProfilePhoto1.getHeight(), Image.SCALE_SMOOTH);
//            viewProfilePhoto1.setIcon(new ImageIcon(image));

        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No File Selected");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void addCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCancelBtnActionPerformed
        txtEmployeeName.setText("");
        txtEmployeeID.setText("");
        txtEmployeeAge.setText("");
        txtEmployeeGender.setSelectedIndex(0);
        txtEmployeeStartDate.setText("");
        txtEmployeeTeam.setText("");
        txtEmployeeLevel.setSelectedIndex(0);
        txtEmployeePosition.setText("");
        txtEmployeeContactNo.setText("");
        txtEmployeeEmailID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_addCancelBtnActionPerformed

    
    
    
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
        String name = txtEmployeeName.getText();
        String employeeID = txtEmployeeID.getText();
        String age= txtEmployeeAge.getText();
        int empAge=0;
        empAge= Integer.parseInt(age);
        String gender=txtEmployeeGender.getSelectedItem().toString();
        String startDate = txtEmployeeStartDate.getText();

        SimpleDateFormat date_formatter = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date();
        date=date_formatter.parse(startDate);
        String level= txtEmployeeLevel.getSelectedItem().toString();
        String teamInfo = txtEmployeeTeam.getText();
        String position = txtEmployeePosition.getText();
        String phone = txtEmployeeContactNo.getText();
        String emailID = txtEmployeeEmailID.getText();

        String photo = add_emp.getImgPath();
        
        if (age!=null && !age.isEmpty() && name!=null && !name.isEmpty() && employeeID!=null && !employeeID.isEmpty() && gender!=null && !gender.isEmpty() && level!=null && !level.isEmpty() && teamInfo!=null && !teamInfo.isEmpty() && position!=null && !position.isEmpty() && phone!=null && !phone.isEmpty() && emailID!=null && !emailID.isEmpty() &&  photo!=null && !photo.isEmpty() && name_pattern.matcher(name).matches() && phone_pattern.matcher(phone).matches() && email_pattern.matcher(emailID).matches()){
            JOptionPane.showMessageDialog(addBtn,"Employee data is successfully added");
            Employee emp= add_emp.addNewEmployee();
        emp.setName(name);
        emp.setEmployeeID(employeeID);
        emp.setAge(empAge);
        emp.setGender(gender);
        emp.setStartDate(date);
        emp.setLevel(level);
        emp.setTeamInfo(teamInfo);
        emp.setPosition(position);
        emp.setPhone(phone);
        emp.setEmailID(emailID);
        emp.setImage(photo);
        employeeTable();
        jTabbedPane1.setSelectedIndex(4);

        txtEmployeeName.setText("");
        txtEmployeeID.setText("");
        txtEmployeeAge.setText("");
        txtEmployeeGender.setSelectedIndex(0);
        txtEmployeeStartDate.setText("");
        txtEmployeeTeam.setText("");
        txtEmployeeLevel.setSelectedIndex(0);
        txtEmployeePosition.setText("");
        txtEmployeeContactNo.setText("");
        txtEmployeeEmailID.setText("");
        }
        else{
           JOptionPane.showMessageDialog(addBtn,"Please check the fields!!");  

        }
        }
        catch (Exception e) 
        {
           JOptionPane.showMessageDialog(addBtn,"Please check the fields!!");  
        }
        
        

        

        //    String photo;                   // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void txtEmployeeEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeEmailIDActionPerformed

    private void txtEmployeeContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeContactNoActionPerformed

    private void txtEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeLevelActionPerformed

    private void txtEmployeeGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeGenderActionPerformed

    private void txtEmployeeTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeTeamActionPerformed

    private void txtEmployeeStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeStartDateActionPerformed

    private void txtEmployeePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeePositionActionPerformed

    private void txtEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeAgeActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        String deleteEmployeeID = delEmployeeID.getText();

        Employee temp = null;

        for(Employee emp: add_emp.getEmployee_list()) {
            if(emp.getEmployeeID().equals(deleteEmployeeID)) {
                temp = emp;

            }
           
        }
        add_emp.getEmployee_list().remove(temp);
        JOptionPane.showMessageDialog(deleteBtn,"Employee data is successfully deleted");
        jTabbedPane1.setSelectedIndex(4);
        employeeTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeNameActionPerformed

    private void editEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeLevelActionPerformed

    private void editEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeAgeActionPerformed

    private void editEmployeeTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeTeamActionPerformed

    private void editEmployeeGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeGenderActionPerformed

    private void editEmployeeEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeEmailIDActionPerformed

    private void editEmployeePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeePositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeePositionActionPerformed

    private void editEmployeeStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeStartDateActionPerformed

    private void editEmployeeContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeContactNoActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int edit = employeeTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        if(edit>=0){
            model.setValueAt(editEmployeeName.getText(), edit, 0);
            model.setValueAt(editEmployeeID.getText(), edit, 1);
            model.setValueAt(editEmployeeAge.getText(), edit, 2);
            model.setValueAt(editEmployeeGender.getSelectedItem().toString(), edit, 3);
            model.setValueAt(editEmployeeStartDate.getText(), edit, 4);
            model.setValueAt(editEmployeeTeam.getText(), edit, 5);
            model.setValueAt(editEmployeeLevel.getSelectedItem().toString(), edit, 6);
            model.setValueAt(editEmployeePosition.getText(), edit, 7);
            model.setValueAt(editEmployeeContactNo.getText(), edit, 8);
            model.setValueAt(editEmployeeEmailID.getText(), edit, 9);
            JOptionPane.showMessageDialog(addBtn,"Employee data is edited successfully");
            jTabbedPane1.setSelectedIndex(4);
            editEmployeeName.setText("");
            editEmployeeID.setText("");
            editEmployeeAge.setText("");
            editEmployeeGender.setSelectedIndex(0);
            editEmployeeStartDate.setText("");
            editEmployeeTeam.setText("");
            editEmployeeLevel.setSelectedIndex(0);
            editEmployeePosition.setText("");
            editEmployeeContactNo.setText("");
            editEmployeeEmailID.setText("");

        }
        else{
            JOptionPane.showMessageDialog(null,"Please select a row from the table");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void editCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCancelBtnActionPerformed
        // TODO add your handling code here:
        editEmployeeName.setText("");
        editEmployeeID.setText("");
        editEmployeeAge.setText("");
        editEmployeeGender.setSelectedIndex(0);
        editEmployeeStartDate.setText("");
        editEmployeeTeam.setText("");
        editEmployeeLevel.setSelectedIndex(0);
        editEmployeePosition.setText("");
        editEmployeeContactNo.setText("");
        editEmployeeEmailID.setText("");
    }//GEN-LAST:event_editCancelBtnActionPerformed

    private void viewEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeNameActionPerformed

    private void viewEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeAgeActionPerformed

    private void viewEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeLevelActionPerformed

    private void viewEmployeeGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeGenderActionPerformed

    private void viewEmployeeTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeTeamActionPerformed

    private void viewEmployeeEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeEmailIDActionPerformed

    private void viewEmployeePositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeePositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeePositionActionPerformed

    private void viewEmployeeContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeContactNoActionPerformed

    private void viewEmployeeStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmployeeStartDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewEmployeeStartDateActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void viewPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPageMouseClicked
       
    }//GEN-LAST:event_viewPageMouseClicked

    private void deleteCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCancelBtnActionPerformed
        delEmployeeID.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCancelBtnActionPerformed

    
    
    //function when user clicks add button
    
    
    //function when user clicks delete button
    
    
    //function when user clicks edit button
    
  //function when user clicks cancel button(Edit)
    
//function when user clicks search button
    
    
//function to populate row-content of table to edit page
    
      //function when user clicks cancel button(Add)

    
 //function when user clicks cancel button(Search)
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagementPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagementPortal().setVisible(true);
            }
        });
    }
    
//function to add content to the table    
    private void employeeTable(){
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        model.setRowCount(0);
        for(Employee emp: add_emp.getEmployee_list()){
            Object[] row = new Object[13];
            row[0]=emp.getName();
            row[1]=emp.getEmployeeID();
            row[2]=emp.getAge();
            row[3]=emp.getGender();
            SimpleDateFormat date_formatter = new SimpleDateFormat("dd-MM-yyyy");
            row[4]=date_formatter.format(emp.getStartDate());
            row[6]=emp.getLevel();
            row[5]=emp.getTeamInfo();
            row[7]=emp.getPosition();
            row[8]=emp.getPhone();
            row[9]=emp.getEmailID();
            row[10]=emp.getImage();
            System.out.println(row[10]+"this is img");
           model.addRow(row) ;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addCancelBtn;
    private javax.swing.JPanel addPage;
    private java.awt.Button button1;
    private javax.swing.JTextField delEmployeeID;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton deleteCancelBtn;
    private javax.swing.JPanel deletePage;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton editCancelBtn;
    private javax.swing.JTextField editEmployeeAge;
    private javax.swing.JTextField editEmployeeContactNo;
    private javax.swing.JTextField editEmployeeEmailID;
    private javax.swing.JComboBox<String> editEmployeeGender;
    private javax.swing.JTextField editEmployeeID;
    private javax.swing.JComboBox<String> editEmployeeLevel;
    private javax.swing.JTextField editEmployeeName;
    private javax.swing.JTextField editEmployeeName1;
    private javax.swing.JTextField editEmployeePosition;
    private javax.swing.JTextField editEmployeeStartDate;
    private javax.swing.JTextField editEmployeeTeam;
    private javax.swing.JPanel editPage;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchCancelBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel searchPage;
    private javax.swing.JPanel tablePage;
    private javax.swing.JLabel test;
    private javax.swing.JTextField txtEmployeeAge;
    private javax.swing.JTextField txtEmployeeContactNo;
    private javax.swing.JTextField txtEmployeeEmailID;
    private javax.swing.JComboBox<String> txtEmployeeGender;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JComboBox<String> txtEmployeeLevel;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeePosition;
    private javax.swing.JTextField txtEmployeeStartDate;
    private javax.swing.JTextField txtEmployeeTeam;
    private javax.swing.JTextField viewEmployeeAge;
    private javax.swing.JTextField viewEmployeeContactNo;
    private javax.swing.JTextField viewEmployeeEmailID;
    private javax.swing.JComboBox<String> viewEmployeeGender;
    private javax.swing.JTextField viewEmployeeID;
    private javax.swing.JComboBox<String> viewEmployeeLevel;
    private javax.swing.JTextField viewEmployeeName;
    private javax.swing.JTextField viewEmployeePosition;
    private javax.swing.JTextField viewEmployeeStartDate;
    private javax.swing.JTextField viewEmployeeTeam;
    private javax.swing.JPanel viewPage;
    private javax.swing.JLabel viewProfilePhoto1;
    // End of variables declaration//GEN-END:variables
}


