/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secondAssignment.system.ui;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import secondAssignment.system.person.City;
import secondAssignment.system.person.Community;
import secondAssignment.system.person.DoctorDirectory;
import secondAssignment.system.person.Encounter;
import secondAssignment.system.person.EncounterHistory;
import secondAssignment.system.person.House;
import secondAssignment.system.person.Patient;
import secondAssignment.system.person.PatientDirectory;
import secondAssignment.system.person.VitalSigns;

/**
 *
 * @author shubhamjain
 */
public class AddNewPatientRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPatientRecord
     */
    City city;
    PatientDirectory plist;
    DoctorDirectory dlist;

    public AddNewPatientRecord(PatientDirectory plist, City city, DoctorDirectory dlist) {
        initComponents();
        this.plist = plist;
        this.city = city;
        this.dlist = dlist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        txtEmailID = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtResperatory = new javax.swing.JTextField();
        txtweight = new javax.swing.JTextField();
        txtBloodpressure = new javax.swing.JTextField();
        txtTemperature = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(688, 438, -1, -1));

        jLabel1.setText("Patient ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 134, 112, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 172, 112, -1));

        jLabel5.setText("Age");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 204, 112, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 251, 112, -1));
        getContentPane().add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 131, 155, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 172, 155, -1));
        getContentPane().add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 204, 155, -1));
        getContentPane().add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 274, 155, -1));

        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 350, 155, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 450, 112, -1));

        jLabel10.setText("City");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 239, 112, -1));
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 239, 155, -1));

        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 312, 112, -1));

        jLabel12.setText("Community");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 277, 112, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 309, 155, -1));

        jLabel13.setText("Email ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 353, 112, -1));

        jLabel14.setText("Information");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 108, 132, -1));

        jLabel15.setText("Vital Sign");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 108, 132, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Patient Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 29, 177, -1));

        jLabel4.setText("Resperatory");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 134, 87, -1));
        getContentPane().add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 172, 143, -1));

        jLabel6.setText("Heart Rate");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 175, 87, -1));

        jLabel7.setText("Weight");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 207, 87, -1));

        jLabel9.setText("Blood Pressure");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 239, 87, -1));

        jLabel16.setText("Temperature");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 277, 87, -1));
        getContentPane().add(txtResperatory, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 131, 143, -1));
        getContentPane().add(txtweight, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 204, 143, -1));
        getContentPane().add(txtBloodpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 239, 143, -1));
        getContentPane().add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 274, 143, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secondAssignment/system/ui/bb.jpeg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    public static boolean addPatientInformationclientSideValidation(javax.swing.JFrame frame, String patientID, String name, String age, String community, String address, String email) {
        if (Pattern.compile("^[1-9]\\d*$").matcher(patientID).matches() && !patientID.equals("")) {
            System.out.println("Patient ID is valid.");
            if (Pattern.compile("^[a-zA-Z\\s]*$").matcher(name).matches() && !name.equals("")) {
                System.out.println("Name is valid.");
                if (Pattern.compile("^[1-9]\\d*$").matcher(age).matches() && !age.equals("")) {
                    System.out.println("Age is valid.");
                    if (Pattern.compile("^[a-zA-Z\\s]*$").matcher(community).matches() && !community.equals("")) {
                        System.out.println("Community is valid.");
                        if (Pattern.compile("^[a-zA-Z\\s]*$").matcher(address).matches() && !address.equals("")) {
                            System.out.println("Address is valid.");
                            if (Pattern.compile("^[a-zA-Z0-9_+&-]+(?:\\.[a-zA-Z0-9_+&-]+)*"
                                    + "@" + "(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$").matcher(email).matches() && !email.equals("")) {
                                System.out.println("Email ID is valid.");
                                return true;
                            } else {
                                JOptionPane.showMessageDialog(frame, "Email ID is not in specified format", "Alert", JOptionPane.WARNING_MESSAGE);

                            }
                        } else {
                            JOptionPane.showMessageDialog(frame, "Address is not valid. Only characters and spaces are allowed", "Alert", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(frame, "Community is not valid. Only characters and spaces are allowed", "Alert", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(frame, "Age is not valid. Only numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(frame, "Name field is not valid. Only characters and spaces are allowed", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(frame, "Patient ID is not valid. Only numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
        return false;
    }

    public static boolean addPatientVitalSignsclientSideValidation(javax.swing.JFrame frame, String bp, String pulse, String bt, String respiration, String weight) {
        if (Pattern.compile("^[1-9]\\d*$").matcher(respiration).matches() && !respiration.equals("")) {
            System.out.println("Respiration field is valid.");
            if (Pattern.compile("^[1-9]\\d*$").matcher(pulse).matches() && !pulse.equals("")) {
                System.out.println("Heart field is valid.");
                if (Pattern.compile("^[1-9]\\d*$").matcher(weight).matches() && !weight.equals("")) {
                    System.out.println("Weight field is valid.");
                    if (Pattern.compile("^[1-9]\\d*$").matcher(bp).matches() && !bp.equals("")) {
                        System.out.println("Blood pressure field is valid.");
                        if (Pattern.compile("^[1-9]\\d*$").matcher(bt).matches() && !bt.equals("")) {
                            System.out.println("Temperature field is valid.");
                            return true;

                        } else {
                            JOptionPane.showMessageDialog(frame, "Temperature field is not valid. Only Numbers are allowed..", "Alert", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(frame, "Blood pressure field is not valid. Only Numbers are allowed..", "Alert", JOptionPane.WARNING_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(frame, "Weight field is not valid. Only Numbers are allowed..", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(frame, "Heart field is not valid. Only Numbers are allowed..", "Alert", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(frame, "Respiration field is not valid. Only Numbers are allowed..", "Alert", JOptionPane.WARNING_MESSAGE);
        }
        return false;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

//        if (!validateInput()) {
//            JOptionPane.showMessageDialog(this, "Enter valid details.");
//        }
        String name = txtName.getText();
        String id = txtPatientID.getText();
        String age = txtage.getText();
        String email = txtEmailID.getText();
        String residence = txtAddress.getText();
        String community = txtCommunity.getText();

        Community c1 = city.getCommunity(community);
        House house = new House(residence);
        if (c1.getCommunityName() != null) {
            c1.addHouse(house);
            System.out.println("Old community found:" + c1.getCommunityName());
        } else {
            c1.setCommunityName(community);
            c1.addHouse(house);
            city.addCommunity(c1);

            System.out.println("New community added:" + c1.getCommunityName());

        }
        boolean passed = addPatientInformationclientSideValidation(this, id, name, age, community, residence, email);
        if (passed) {
            int patientid = Integer.parseInt(id);
            int patientAge = Integer.parseInt(age);

            String bp = txtBloodpressure.getText();
            String pulse = txtHeartRate.getText();
            String bt = txtTemperature.getText();
            String respiration = txtResperatory.getText();
            String weight = txtweight.getText();

//      Integer bp = Integer.parseInt(txtBloodpressure.getText());
//      Integer pulse = Integer.parseInt(txtHeartRate.getText());
//      Integer bt = Integer.parseInt(txtTemperature.getText());
//      Integer respiration = Integer.parseInt(txtResperatory.getText());
//      Integer weight= Integer.parseInt(txtweight.getText());
            boolean passed1 = addPatientVitalSignsclientSideValidation(this, bp, pulse, bt, respiration, weight);

            Double bp1 = Double.parseDouble(bp);
            Double pulse1 = Double.parseDouble(pulse);
            Double bt1 = Double.parseDouble(bt);
            Double respiration1 = Double.parseDouble(respiration);
            Double weight1 = Double.parseDouble(weight);
            if (passed1) {
                String timestamp = new SimpleDateFormat("MM/dd/yyyy hh:mm:ss").format(Calendar.getInstance().getTime());

                EncounterHistory encounterHistory = new EncounterHistory();
                VitalSigns vitalSigns = new VitalSigns(pulse1, bp1, weight1, respiration1, bt1);
                Encounter encounter = new Encounter(vitalSigns, timestamp);
                encounterHistory.addNewEncounter(encounter);
                Patient pat = new Patient(encounterHistory, name, patientid, patientAge, email, city, house, c1);
                plist.addPatient(pat);

                JOptionPane.showMessageDialog(this, "New Patient added.");
                setVisible(false);
                new AddNewPatientRecord(plist, city, dlist).setVisible(true);
//      txtName.setText("");
//      txtPatientID.setText("");
//      txtage.setText("");
//      txtEmail.setText("");
//      txtAddress.setText("");
//      txtCommunity.setText("");
//      txtCity.setText("");
//      txtBP.setText("");
//      txtHR.setText("");
//      txtTemperature.setText("");
//      txtRespiratoryRate.setText("");
//      Weight.setText("");
//        String patientID = txtPatientID.getText();
//        String name = txtName.getText();
//        String contactNumber = txtage.getText();
//        String age = txtCommunity.getText();
//        String gender = (String) cmbGender.getSelectedItem();
//        String address = txtAddress.getText();
//        String bloodgroup = txtEmailID.getText();
//        String majorDisease = txtMajorDisease.getText();
//        try{
//          JOptionPane.showMessageDialog(null, "Succesfully saved");
//          setVisible(false);
//          new AddNewPatientRecord().setVisible(true);
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Please enter correct data");
//            
//        }
                //       }
                //      
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

//    private boolean validateInput() {
//        if (txtName.getText().isEmpty() || txtPatientID.getText().isEmpty() || txtage.getText().isEmpty()
//                || txtEmailID.getText().isEmpty() || txtAddress.getText().isEmpty() || txtCommunity.getText().isEmpty()
//                || txtCity.getText().isEmpty() || txtBloodpressure.getText().isEmpty() || txtHeartRate.getText().isEmpty() || txtTemperature.getText().isEmpty()
//                || txtResperatory.getText().isEmpty() || txtweight.getText().isEmpty()) {
//            return false;
//
//        }
//        return true;
//    }

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AddNewPatientRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AddNewPatientRecord().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBloodpressure;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtEmailID;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtResperatory;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtweight;
    // End of variables declaration//GEN-END:variables
}
